export * from './home';
export * from './news';
export * from './notices';
export * from './registration';
export * from './addPet';
export * from './friends';
export * from './notFound';
export * from './login';
export * from './profile';
